name: pull_request
on: pull_request
jobs:
  lint-formatting-unit-tests:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install packages
        run: |
          dart pub get
          cd example
          flutter pub get
          cd ..
      - name: Lint
        run: dart analyze
      - name: Ensure correct formatting
        run: dart format --set-exit-if-changed .
      - name: Unit tests
        run: dart test
      - name: Ensure flappy_translator works
        run: |
          cd example
          dart run flappy_translator
